<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>开发错误</title>
</head>
<style>
    h1{font-size:100px;text-align:center;margin:0;padding:0;font-family:KaiTi}
    h2{text-align: center;}
    a{color: #337ab7;text-decoration: none;}
    a:link,a:visited,a:hover{text-decoration:none;}
</style>
<body>
<div style="height:50px;"></div>
<h1><?php echo !empty($msg)?$msg:'错误信息'; ?></h1>
<?php
$message=isset($info)?$info:'没有详细错误信息！';
?>
<h2><?php print_r($message); ?></h2>
<hr>
<p style="text-align: center"><a href="javascript:history.go(-1);">上一页</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="/">回首页</a></p>
</body>
</html>